# change the default theme to be use when building the site with Hugo
theme = "relearn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]

alwaysopen = true


# Change default color scheme with a variant one.
 themeVariant = [ "gobolinux","relearn-light","relearn-dark","neon","blue","green","learn" ]
# themeVariant = "gobolinux"


# [Languages]
# [Languages.en]

# landingPageURL = "/"
# landingPageName = "<i class='fas fa-home'></i> Home"

# [Languages.pir]
# landingPageURL = "/pir/"
# landingPageName = "<i class='fas fa-home'></i> Arrr! Homme"

defaultContentLanguage = "en"
disableLandingPageButton = true

[Languages]
[Languages.en]
title = "DSF"
weight = 1
languageName = "English"



[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30
